---
 - name: Create User
   keystone_user: tenant=admin user=neutron password=neutron_pass token=c74441d71bd640660939 state=present

 - name: Add Neutron user to admin role
   keystone_user: user=neutron tenant=service role=admin token=c74441d71bd640660939  state=present

 - name: Create Neutron Service
   keystone_service: name=neutron type=network description="OpenStack Networking" public_url=http://{{ ansible_eth0['ipv4']['address'] }}:9696 token=c74441d71bd640660939

   notify:
   - Neutron restart all    

