---
   - name: Create the user neutron
     keystone_user: tenant=admin user=neutron password=neutron_pass token=c74441d71bd640660939 state=present

   - name: Add neutron user to admin role
     keystone_user: user=neutron tenant=service role=admin token=c74441d71bd640660939  state=present

   - name: Create Neutron service and Endpoint
     keystone_service: name=neutron type=compute description="Neutron Image Service" token=c74441d71bd640660939 public_url=http://localhost:35357/v2.0

   - name: Copy Neutron.conf
     template: src=/etc/ansible/roles/controller/templates/ne.j2 dest=/etc/neutron/neutron.conf owner=root group=neutron mode="u=rw,g=r,o=r"

   - name: Copy ml2_conf.ini
     template: src=/etc/ansible/roles/controller/templates/ml.j2 dest=/etc/neutron/plugins/ml2/ml2_conf.ini owner=root group=neutron mode="u=rw,g=r,o=r"

   - name: Copy Metadata_agent.ini
     template: src=/etc/ansible/roles/controller/templates/meta.j2 dest=/etc/neutron/metadata_agent.ini owner=root group=neutron mode="u=rw,g=r,o=r"

   - name: Copy dhcp_agent.ini
     template: src=/etc/ansible/roles/controller/templates/dhcp.j2 dest=/etc/neutron/dhcp_agent.ini owner=root group=neutron mode="u=rw,g=r,o=r"

   - name: Copy l3_agent.ini
     template: src=/etc/ansible/roles/controller/templates/l3.j2 dest=/etc/neutron/l3_agent.ini owner=root group=neutron mode="u=rw,g=r,o=r" 


   - name: Sync DB
     command: neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade juno

     notify:
     - Neutron restart all
